### ISSUE TITLE
Line numbers in errNoMatch

### ISSUE THREAD

**Issue by tsandall** [mna/pigeon#18] opened 2016-09-23 06:15 UTC
Hi Martin,

The line numbers in errNoMatch errors do not make sense to me. Any help or pointers would be appreciated.

I started to reproduce this with a minimal test case but then realized that I could use an invalid .peg file and run `pigeon` over it to produce the same error...

For example...

```
$ cat blah.peg
```

Output:

```







xxx
```

(yes, a bunch of newlines followed by "xxx" followed by newline).

Then run pigeon over the file to generate the parser...

```
$ pigeon blah.peg
parse error(s):
 blah.peg:2:0 (0): no match found
```

Line 2 doesn't seem to be the problem here. I must be missing something!

**Comment by tsandall** [comment] 2016-09-23 06:18
Here's a minimal-ish grammar that displays the same problem:

```
{
package main

import "fmt"

func main() {
	_, err := Parse("", []byte(`123455`))
	fmt.Println(err)
	_, err = Parse("", []byte(`

	1

	2

	3

	`))
	fmt.Println(err)
	_, err = Parse("", []byte(`

	1

	2

	x
	`))
	fmt.Println(err)
}
}

Program <- _ (X _)* _  EOF

X <- [0-9]

ws "whitespace" <- [ \t\r\n]+

_ "whitespace" <- ( [ \t\r\n] )*

EOF <- !.
```

Output:

```
$ pigeon -o parser.go test.peg
$ goimports -w parser.go
$ go run parser.go
<nil>
<nil>
2:0 (0): no match found
```

**Comment by tsandall** [comment] 2016-10-18 17:50
@PuerkitoBio any chance you could take a look at this? I assume you're busy but I would really appreciate it! ^.^

**Comment by PuerkitoBio** [comment] 2016-10-19 11:29
Hello Torin,

I'm not using this package so unfortunately it's unlikely that I'll have time to commit to this in the near future. I'm open to PRs with good tests and no API change, if anyone can help on this.

Thanks,
Martin

**Comment by tsandall** [comment] 2016-10-24 18:51
As a workaround, I have modified my grammar to include a catch-all rule that simply panics. This way the generated parser will report a more accurate location (at the expense of only returning one error).

**Comment by joshsharp** [comment] 2017-05-15 11:34
I've just come across this issue attempting to use Pigeon for my own project, and tracked down the cause.

For me, the error position is also always 2:0 (0), as the position being used and displayed is that of the start of my first rule, which encompasses the entire input (the same as the Program rule in the above example). The fix is to change the `addError` call inside the `parse` method to `addErrAt`, using the current position and not the fallback of the savepoint's position, which will always be the start of the first rule:

```go
func (p *parser) parse(g *grammar) (val interface{}, err error) {
  // ---snip---
  if len(*p.errs) == 0 {
    // make sure this doesn't go out silently
    p.addErrAt(errNoMatch, p.cur.pos)
  }
}
```

@mna, let me know if you'd like/accept a pull request to fix this (or ideally could change this line yourself!) Thanks :)

**Comment by mna** [comment] 2017-05-15 18:45
Hello Josh,

Thanks for looking into this. Unfortunately, as I mentioned elsewhere in the comments, I don't have much time for this package as I don't use it myself, and it takes considerable time switching back into this codebase given the "inception-like" nature of the project (the bootstrap parser, the parser generator, etc).

I'd definitely accept a PR with good tests that demonstrate the issue before that fix, and how this clearly fixes the problem without creating new ones :)

Otherwise I may get to it eventually, but no promises regarding the date!

Thanks,
Martin

**Comment by joshsharp** [comment] 2017-05-16 00:28
Yeah, I thought that might be the case, but I was hoping you'd save me the trouble of trying to get my own head around it :) I'll see what I can do then, if I'm lucky it'll be a minor change that doesn't break anything else. Thanks

**Comment by breml** [comment] 2017-05-19 20:04
@joshsharp, @tsandall The problem you are facing is, that PEG by design tracks back to the first rule to try other possible paths, if you do not take measures within your grammar. There are two strategies, I am using to increase the meaning of the error reporting:

1. As suggested in https://godoc.org/github.com/mna/pigeon#hdr-Error_reporting, if your grammar is at a position, where backtracking is meaningless (like missing closing doublequotes), then stop the parsing by a panic. In my grammars this looks like this:  
```
doubleQuotedString =
    ( `"` ( `\"` / !`"` . )* (
        `"` / &{
            return fatalError("expect closing double quotes (\")", c)
        }
    ) ) {
        return enclosedValue(c)
    }
```  
This rule matches a double quote followed by an arbitrary number of escaped double quotes or none double quote characters and is ended by either a closing double quote or the predicate which will panic (`fatalError` is a function, which puts together the error with the right text and position and then raises a panic).

2. For parsing errors at positions, where I can't be sure, that it is really an error (because an other parsing path may be successful), I keep track of the farthest error position. This strategy is based on the paper  [Error Reporting in Parsing Expression Grammars](http://arxiv.org/pdf/1405.6646.pdf), which I also mentioned in https://github.com/mna/pigeon/issues/9#issuecomment-228834245.  
In my grammars this looks like this:

```
value =
    stringValue / number / regexp / &{
        return pushError("invalid value for expression", c)
    }
```

In this case, multiple alternatives are checked (`string_value`, `number`, `regexp`) and if none of those alternatives is a match, the `pushError` function adds the potential error to a global slice of errors, under the following conditions:

* If the global slice of errors is empty or the position of the current error is larger than the position of the already stored error(s), then the error slice is replaced by a new slice only containing the current error.
* If the position of the already stored error(s) is the same as the position of the current error, the current error is added to the slice.

Now, when the parser is done and it finishes with an error, I lookup the farthest errors. If there are errors stored, those are returned to the user. This strategy proved it self as quite accurate. By this I mean that in most cases, the actual error is at or very close to the position of the farthest error.

I hope, these explanations help you to improve your parser(s).

In pigeon, for me there is one thing that would improve the design of my parser. If there would be something like a global store (not state as in #16), I would place the farthest errors into this global store. Currently I use a package global variable, which is not quite clean and it also prevents me from using the parser concurrently. Maybe I will create an PR for this.

**Comment by joshsharp** [comment] 2017-05-20 06:04
@breml thanks for this explanation! That's really handy. Having previously only built lexers and parsers on EBNF grammars, I'm still yet to get used to the idea that I should be adding rules to my grammar that specifically match *incorrect* syntax, and would ideally prefer that the parser generate lovely, useful syntax errors for me :) But your explanation helps me see the value of doing it this way, and gives me some ideas about how to implement it myself.

Just to clarify, are you saying that the current behaviour in `parse`, using the position of the outer rule as the error position, is correct/useful behaviour that shouldn't be modified as per my suggestion?

**Comment by breml** [comment] 2017-05-21 20:09
@joshsharp I am absolutely with you regarding
> prefer that the parser generate lovely, useful syntax errors for me :)
but as mentioned in by @mna in [reddit thread](https://www.reddit.com/r/golang/comments/32filp/a_peg_parser_generator_for_go/), it is not a trivial task to return something more useful automatically.
I think, there is some room for improvement, especially if I compare to the error messages provided by [pegjs](https://pegjs.org).
Any help to improve the error reporting or to investigate, how the error reporting is done e.g. in pegjs, would be appreciated.

 > Just to clarify, are you saying that the current behaviour in parse, using the position of the outer rule as the error position, is correct/useful behaviour that shouldn't be modified as per my suggestion?

Yes, I think, that the current behavior in parse is the correct behavior due to the built in backtracking in PEG. If you run pigeon with the `-debug` flag set, you will see, that the parser performs a backtracking until the back to the very first rule, where the parser has no more options to move forward, which results in the `no match found` error.
That being said, I am not sure, that it is the most useful behavior in regards of error reporting. As said above, in my opinion pegjs does a better job in providing meaningful error messages. I am certain, that this could be improved for pigeon as well (see also the linked paper).
The possible improvements would be based on some sort of heuristic within pigeon, which tries in those situations to provide the most probable error position. As stated in the above mentioned paper, in most cases, the real error position is close to the farthest position, until which the parsing was successful (before the backtracking started).

I hope this helps to clarify.

**Comment by joshsharp** [comment] 2017-05-22 05:44
I had a play with pegjs' online version, and the errors seem pretty nice for something out of the box, for example it will provide examples of matching rules:

```
2 * (3 / 4
```
```
Line 1, column 11: Expected ")", "*", "+", "-", or "/" but end of input found.
```

I'll have a look at the implementation and see how feasible it is to borrow its ideas.

**Comment by breml** [comment] 2017-05-25 19:41
@joshsharp I had a look at the source of pegjs my self and I found the function [peg$fail](https://github.com/pegjs/pegjs/blob/master/lib/parser.js#L602-L611), which does pretty much the same as the function I am using in my grammars. Therefore I think it makes sense to give a similar implementation in pigeon a try. The call to this "record error position" function has to be called when ever the parsing failed and the backtracking starts.
I think, that to globalStore feature, implemented in #23, could be used to store the necessary information. What do you think?
I will have a look at pigeon to figure out, where it has to be changed to support this (any help is of course appreciated).

**Comment by joshsharp** [comment] 2017-05-28 07:47
Oh, I somehow missed you are the new maintainer, @breml! Congrats :)

I also found `peg$fail` in peg.js but I don't understand pigeon well enough to work out how I'd integrate it and get it to include the required error handling into the generated parser. I might have some time in future to try and understand it and have a go, but I still consider myself very much a Go newbie at this stage, so any progress I make will probably be slow.

If you take a look and find it feasible, do you think this is something that will make it into the 2.0 release the README now mentions?

**Comment by breml** [comment] 2017-05-28 22:06
@joshsharp I only quite recently became the new maintainer (less than a week ago). So let's see, where we can drive pigeon.

I just filed two new PR (#24 and #25), which implement the improved error handling (currently as an optional feature).

As mentioned in the PR, I would appreciate your help with testing and support for the documentation.

I will try the new functionality in my own parsers in the next few days.

**Comment by joshsharp** [comment] 2017-05-29 07:35
Wow, you move fast! This is amazing.

I will try to find time to test this out with my parser in the next few days. I've looked at the diff for doc.go and your additions are perfectly fine also. Thanks!

**Comment by breml** [comment] 2017-05-30 05:31
@tsandall Added your minimal-ish grammar from https://github.com/mna/pigeon/issues/18#issuecomment-249111959 to https://github.com/mna/pigeon/pull/25/commits/5e64857a848b4789928c6400609ae24b20f4714e. With the new parser flag `FailureTracking(true)` the error output now becomes:

```
<nil>
<nil>
7:5 (20): no match found, expected: [ \t\r\n], [0-9] or EOF
```

This looks much better.

**Comment by tmc** [comment] 2017-05-30 05:36
This is great to see!

**Comment by tmc** [comment] 2017-05-30 05:38
I have a non-trivial use of pigeon in my https://github.com/tmc/graphql package that could benefit from this work in a meaningful way.

**Comment by breml** [comment] 2017-05-30 05:56
@tmc Thanks for your feedback. I have two questions to you:

* Do you think you would find the time to give this PR a try and use it with your project. It would be great to get some feedback about this feature in real world use cases before I merge this one.
* Do you think the new error reporting should be the default case or provided as an option (the way it is currently implemented)?

**Comment by tmc** [comment] 2017-05-30 06:00
I'm happy to try it out. I can't think of why anyone wouldn't want more detailed errors.

**Comment by joshsharp** [comment] 2017-05-30 06:22
FWIW I definitely think this should be the default.

I would personally like to see "caret style errors" with the offending line included, something like:

```
x + 4 - /
        ^ 
Line 7, column 5: no match found, expected: [ \t\r\n], [0-9] or EOF
```

But I'm not picky! This should be possible to add later (maybe something I can do).

**Comment by breml** [comment] 2017-05-30 06:41
@joshsharp I was also thinking about "caret style errors" and it is something I would like to have as well. But I am not sure yet how to do this, because every author has its own preference how he would like to present or log errors. Therefore I think, it would be the best to return errors, which include all the details (line, column, offset, expected characters, maybe context) and then let the user decide, how he wants to present the error to the user. The above is just the default case, when someone simply prints the error.

An other option would be to provide the user an Option, which lets him format the errors. I will think about this.

**Comment by joshsharp** [comment] 2017-05-30 07:01
Good point, of course we can present this in another format if we like :) I think that's a perfect base implementation then.

**Comment by tsandall** [comment] 2017-05-31 22:18
@breml I tried out #25 and found it does improve the error reporting. However, I think the grammar I tested it on will need to be refactored (substantially) to benefit from the new reporting. E.g., right now the errors look like this:

```
no match found, expected: "#", "-", ".", "0", "[", "\"", "default", "false", "import", "not", "null", "package", "set(", "true", "{", [ \t\r\n], [ \t], [1-9], [A-Za-z_] or EOF
```

Or...

```
no match found, expected: "!=", "#", "&", "*", "+", ",", "-", ".", "/", "0", ":", "<", "<=", "=", ">", ">=", "[", "\"", "false", "not", "null", "set(", "true", "with", "{", "|", "}", [ \t\r\n], [ \t], [1-9], [A-Za-z_]
```

The grammar in question is here: https://github.com/open-policy-agent/opa/blob/master/ast/rego.peg (I'm open to suggestions on how to structure it more idiomatically in case that'll help with the error messages.)

I'll try to apply your suggestions from above and see how much of improvement they provide. Thanks!

**Comment by breml** [comment] 2017-06-01 12:59
@tsandall Thanks for your testing and the feedback. I am glad, that you observe an improvement. Your observation, that in some cases, the new (automatically) generated error message is not very helpful due to the large list of possible expected values, does not come as a surprise to me. This is also mentioned in the paper, where I took the idea from for the "Track Farthest Failure" implementation.

> An analysis of the test cases available in the parser package shows us that around half of the expected error messages have a list of at least eight expected tokens (there were messages with a list of 39 expected tokens).

In the mentioned paper there is a second strategy mentioned, called "Labeled Failures", which comes with an extension of the PEG syntax, and which allows for better (more specific) error handling and therefore error messages. The paper also says, that both strategies could be combined, such that as a default the "Track Farthest Failure" is used and "Labeled Failures" are placed, where otherwise the error message would be to verbose or meaning less. The downside of the "Labeled Failures" of course are, that they require the author of the grammar to explicitly add them to the right places within the grammar (and maintain them).

In regards to your grammar, I am not sure, if it is possible to refactor it in a way, that the error messages would become better, because at a certain position within the input you parse, all the mentioned characters will be allowed (and are therefore expected). If the parsing has this position as the farthest position, this will always be the list of allowed characters.

If time allows, I will also have a look at this second error handling strategy in more detail and try to implement it for pigeon.

Last question: I understand, that this feature is at least better as the current state and should therefore be merged. Do you think, it should be the new default or do you think it should be optional (flag)?

**Comment by tsandall** [comment] 2017-06-01 15:41
I don't know what your requirements are around backwards compatibility so it's tough to say. Previously the errors were not structured (e.g., just returns as `errors.New(...)`) I believe. Given this, I don't think many would rely on them programmatically.

In my case, it won't matter (as I was using a catch-all rule that panics to workaround the line number issue.)

If you're worried about backwards compatibility, then it would be better to make it optional.

Otherwise I would just make it the default. It should be safe IMO.

**Comment by breml** [comment] 2017-06-02 05:02
@tsandall Thanks for your feedback. In the discussion above with @joshsharp I already mentioned, that I also want to improve the returned errors, such that they include position and expected literals/characters, which would then allow the user to print nicer error messages (e.g. caret style errors or group multiple expected literals/character classes to more meaningful error messages).
The reason, why I asked @mna to create a 1.0 release prior to the handover to me was, that I wanted to have some headroom to modify/optimize the API. So in the case of the new/improved error messages, I now think, that I will make it the new default.

@tsandall Did you also had a look at #23 as a solution for your issue regarding accessing the filename (#8)?

**Comment by tmc** [comment] 2017-06-02 05:22
For what it's worth I've incorporated this patch into a test branch of https://github.com/tmc/graphql and the errors are much more specific (but a little verbose as some have pointed out). Here is my grammar: https://github.com/tmc/graphql/blob/master/graphql.peg I made minor modifications in that I removed a few of these sort of catch-alls: https://github.com/tmc/graphql/blob/master/graphql.peg#L17-L19

**Comment by joshsharp** [comment] 2017-06-02 11:54
I've finally had a chance to try this and I have a similar error with the grammar I'm working on.

```
let a = 3;
let 😐 = 45;

ERROR:
2:5 (15): no match found, expected: "'", "()", "*", "*.", "+", "++", "+.", "-", "-.", "/", "/.", ";", "<", "<=", "==", "===", ">", ">=", "False", "True", "\"", "^", "_", "and", "not", "or", [ \r\n\t], [0-9], [A-Z], [a-z]
```

It could just be that I don't understand how the error tracking works. In this case I would expect that it fails inside my assignment rule:

```
"let" __ i:Assignable rest:(',' _ Assignable)* _ '=' _ expr:Expr _
```
where Assignable is much smaller subset of the above possible characters:

```
Assignable = VariableName / Unused

VariableName = ([a-z]+ [a-zA-Z0-9_]*) 
Unused = ('_')
```

Instead my guess is that it's backtracking and matching a much broader rule.

I'm not sure if the issue is with my grammar or my expectations of the error tracking. Is it correct behaviour that it would backtrack and end up matching something broader, or in this case is it fair to expect the output to be `no match found, expected: [a-z], '_'`?

**Comment by breml** [comment] 2017-06-02 22:00
@joshsharp from a first sight I also would expect the output to be `no match found, expected: [a-z], '_'`.

I did a quick test with `issue_18a.peg`:
```
{
    package main
}
let = "let" __ i:Assignable

Assignable = VariableName / Unused

VariableName = ([a-z]+ [a-zA-Z0-9_]*) 
Unused = ('_')
__ = [ ]
```

and `issue_18a_test.go`:
```
package main

import "testing"

func TestIssue18a(t *testing.T) {
	if _, err := Parse("", []byte("let 😐 ="), FailureTracking(true)); err != nil {
		t.Fatal(err)
	}
	if _, err := Parse("", []byte("a\xffb")); err == nil {
		t.Fatal("want error on invalid byte sequence")
	} else {
		t.Log(err)
	}
}
```

Generated the parser with the new `pigeon` and ran the tests with `go test -v .`, which produces the following output for me:
```
=== RUN   TestIssue18a
--- FAIL: TestIssue18a (0.00s)
        issue_18a_test.go:7: 1:5 (4): no match found, expected: "_", [a-z]
FAIL
exit status 1
FAIL    github.com/mna/pigeon/test/issue_18a    0.244s
```

So I assume, that zour problem must some how be related to the grammar.

**Comment by joshsharp** [comment] 2017-06-03 07:20
Sure, but imagine I had a slightly larger grammar:

```
{
package main
}

Statement = Let / BinOp
Let = "let" __ i:Assignable
BinOp = VariableName __ ([+|-|/|*]) __ VariableName
Assignable = VariableName / Unused
VariableName = ([a-z]+ [a-zA-Z0-9_]*)
Unused = ('_')
__ = [ ]
```

If I test the same line `let 😐 =` with that grammar, I get:

```
1:5 (4): no match found, expected: "_", [+|-|/|*], [a-z]
```

What I think this demonstrates is that, not having matched Let, it moves on to matching the next rule, because the string `let` can also qualify as a variable name. If that's intended behaviour, that's fine, it's just me misunderstanding how tracking the farthest error works. I'm not sure how to get around this other than to go back to your original suggestion and add specific error rules to my grammar, as also [mentioned in the docs](https://godoc.org/github.com/mna/pigeon#hdr-Error_reporting). I probably should've done this initially instead of being lazy and hoping the parser would do it for me.

I still think this is more useful behaviour that should become the default, regardless :)

**Comment by breml** [comment] 2017-06-03 21:04
@joshsharp For me the important question was, if there is a bug in the "farthest parse pos" heuristic. As I understand your grammar and your example, this is not the case.

With specific error rules, the situation could surely be improved. 

I asked my self, if "let" should be allowed as a variable name at all (maybe there is a list of reserved words). If this is the case, those reserved words should be excluded for variable names. The result would be, that the parsing for `Assignable` would fail at an earlier position and would therefore not add more possible values to the list of expected.

To exclude the reserved words, something like this could be used:

```
reserved = ("let" / "if" / "else" ... ) ![a-z]+
variableName = !reserved ([a-z]+ [a-zA-Z0-9_]*)
```

**Comment by joshsharp** [comment] 2017-06-04 02:36
I had been thinking about a similar solution, actually! That'll work just fine. Sorry for the confusion on my end.

**Closed** 2017-06-04 15:41 UTC

**Comment by breml** [comment] 2017-06-04 16:00
Merged the failure tracking based on the farthest parse failure into master and made the new behavior the default (no flag for the old behavior), as I am convinced, that the new behavior provides better (while some times verbose and not perfect) error messages. It is also my understanding, that the participants in this issue agree to this point of view.
@tsandall, @tmc, @joshsharp Thank you very much for your testing and the feedback you provided.
